import torch

FORCE_SAMPLE_COUNT = 256
FORCE_CHANNEL_COUNT = 3
FORCE_CURVE_DURATION = 4.0
PHRASE_WORD_COUNT = 3
FORCE_EMBEDDING_DIM = FORCE_SAMPLE_COUNT * FORCE_CHANNEL_COUNT
DEVICE = torch.device('cpu')
